config/routes.rb
TrustyCms::Application.routes.draw do
  root to: 'site#show_page'
  devise_for :users, module: :devise, skip: :registration
  as :user do
    post 'authenticate', to: 'devise/sessions#create', as: :authenticate
  end
  get '/rad_social/mail' => 'social_mailer#social_mail_form', as: :rad_social_mail_form
  post '/rad_social/mail' => 'social_mailer#create_social_mail', as: :rad_create_social_mail
  TrustyCms::Application.config.enabled_extensions.each do |ext|
  end
  namespace :admin do
    resources :pages do
      resources :children, controller: 'pages'
      get 'remove', on: :member
    end
    resources :layouts do
      get 'remove', on: :member
    end
    resources :users do
      get 'remove', on: :member
    end
    resources :snippets do
      get :remove, on: :member
    end
    post 'save-table-position' => 'pages#save_table_position', as: 'save_tables_position'

    resources :assets do
      get :remove, on: :member
      get :refresh, on: :collection
      put :refresh, on: :member
    end
    resources :page_attachments, only: [:new] do
      get :remove, on: :member
    end
    resources :pages do
      get :remove, on: :member
      resources :page_attachments
    end
  end

  match 'admin/preview' => 'admin/pages#preview', :as => :preview, :via => %i[post put]
  get 'admin' => 'admin/pages#index'

  namespace :admin do
    resource :preferences
    resource :configuration, controller: 'configuration'
    resources :extensions, only: :index
    resources :page_parts
    resources :page_fields
    match '/reference/:type(.:format)' => 'references#show', :as => :reference, :via => :get

    resources :sites do
      get :remove, on: :member
      post :move_higher, on: :member
      post :move_lower, on: :member
      put :move_to_top, on: :member
      put :move_to_bottom, on: :member
    end
  end

  get 'error/404' => 'site#not_found', :as => :not_found
  get 'error/500' => 'site#error', :as => :error
  get '*url' => 'site#show_page'
end

app/views/admin/pages/_asset_popups.html.haml
- render_region :asset_popups do |popups|
  - popups.upload_asset do
    #upload_asset.popup{:style => 'display: none; width: 28em'}
      #upload_asset_busy.busy{:style => 'display: none'}= image('spinner.gif', :alt => '')
      
      .popup_title= t('clipped_extension.upload_asset')

      = form_for([:admin, Asset.new], :html => {:method => 'post', :multipart => true, :class => 'upload_asset'}) do |f|
        = hidden_field_tag 'for_attachment', 1
        = hidden_field_tag 'page_id', @page.id
        #upload-controls
          %p
            %label.custom-file-upload
              = t('clipped_extension.choose_file')
              = f.file_field :asset, :class => 'file', :multiple => true
              #upload-status{:style => 'display: none;'}
                %img{:src => '/assets/admin/spinner.gif'}
          %p
            %a#attach-popup{:href=>'#attach_asset', :style => 'color: #666; font-size: .8em'}= t('clipped_extension.attach_existing')

  - popups.attach_asset do
    #attach_asset.popup{:style=>'display: none;'}
      
      .popup_title= t('clipped_extension.find_assets')
      
      .toolbar
        = render :partial => 'admin/assets/search'
      
      #assets_table.assets.viewport
        - assets = Asset.all.paginate(:per_page => 20, page: params[:p])
        = render :partial => 'admin/assets/asset_table', :locals => {:assets => assets, :with_pagination => true}
    
      .busy{:style => 'display: none'}= image('spinner.gif', :alt => '')
      .buttons
        %a.cancel.close_popup{:href=>'#'}= t('close')
        %a{:href=>'#upload_asset', :id=> 'upload_asset_link', :style => 'color: #666; float: left'}= t('clipped_extension.upload_asset')

app/views/admin/pages/_assets.html.haml
= stylesheet_link_tag 'admin/assets'
= javascript_include_tag 'admin/assets_admin'

%fieldset.asset_attachment
  #attachment_list.assets
    %ul#attachment_fields{:class => @page.page_attachments.empty? ? 'empty' : ''}
      = render :partial => 'admin/page_attachments/attachment', :collection => @page.page_attachments
  .attach-assets
    .message
      - if @page.page_attachments.empty?
        = t('clipped_extension.no_attached_assets')
    = link_to 'path/to/page.html' '#attach_asset', :class => 'button', :id => 'attach_assets' do
      %i.far.fa-image
      = t('clipped_extension.assets')

app/views/admin/pages/_fields.html.haml
= fields.hidden_field :lock_version
= fields.hidden_field :parent_id
= fields.hidden_field :class_name

= render_region :form_top, :locals => {:f => fields}

- render_region :form, :locals => {:f => fields} do |form|
  - form.edit_title do
    %p.title
      %label{:for=>'page_title'}= t('page_title')
      = fields.text_field :title, :class => 'textbox', :required => true
  - form.edit_extended_metadata do
    .drawer
      .drawer_contents#attributes
        %table.fieldset
          = render :partial => 'meta_row', :collection => @meta, :locals => {:f => fields}
          = render :partial => 'admin/page_fields/page_field', :collection => @page.fields
          = render_region :extended_metadata, :locals => {:f => fields}
      .drawer_handle
        %a.toggle{:href=>'#attributes', :rel=>'toggle[attributes]', :class=>"#{(meta_errors? ? 'less' : 'more')}"}
          = meta_label
          %i.fas.fa-angle-down
  - form.edit_page_parts do
    #tab_control
      #tabs.tabs
        #tab_toolbar
          %a.popup{:href=> '#add_part_popup', :title=>t('add_part')}
            %i.fas.fa-plus-circle
      #pages.pages
        = render :partial => 'admin/page_parts/page_part', :collection => @page.parts
    = render_region :parts_bottom, :locals => {:f => fields}

.set
  - render_region :layout, :locals => {:f => fields} do |layout|
    - layout.edit_layout do
      .layout
        = fields.label :layout_id, t('layout')
        = fields.select :layout_id, [[t('select.inherit') , '']] + Layout.all.map { |s| [s.name, s.id] }
    - layout.edit_type do
      .page-type
        = fields.label :class_name, t('page_type')
        = fields.select :class_name, [[t('select.normal'), '']] + Page.descendants.map { |p| [p.display_name, p.name] }.sort_by { |p| p.first }
    - layout.edit_status do
      .status
        = fields.label :status_id, t('status')
        = fields.select :status_id, status_to_display
    - layout.edit_published_at do
      .published-date
        #published_at{:class => (@page.published? ? nil : 'hidden')}
          = fields.label :published_at, t('published_on')
          = fields.text_field :published_at, :class=> 'date', :type=>'date', :value => (@page.published_at? ? I18n.localize(@page.published_at.to_date, :format =>:default) : nil)
    = render_region :layout_row, :locals => {:f => fields}

- render_region :form_bottom, :locals => {:f => fields} do |form_bottom|
  - form_bottom.edit_buttons do
    - @buttons_partials.each do |partial|
      = render :partial => partial, :locals => {:f => fields}
    .page-actions
      = save_model_button(@page)
      = save_model_and_continue_editing_button(@page)
      = submit_tag(t('preview', :default => 'Preview'), :class => 'button', :id => 'show-preview')
      = t('or')
      = link_to t('cancel'), admin_pages_url, class: 'alt'
    #preview_panel.fullcover.grey_out{:style => 'display: none;'}
      %iframe{:id => 'page-preview', :class => 'fullcover', :name => 'page-preview', :src =>  ActionController::Base.relative_url_root.to_s + '/loading-iframe.html', :frameborder => 0, :scrolling => 'auto'}
      .preview_tools
        =submit_tag(t('buttons.save_changes'), :class => 'big save_changes')
        =submit_tag(t('buttons.save_and_continue'), :class => 'big save_and_continue', :name => 'continue')
        %span.info
          = t('or')
          =link_to(t('edit_page'),{}, :class => 'cancel')
  - form_bottom.edit_timestamp do
    = updated_stamp @page

app/views/admin/pages/_meta_row.html.haml
%tr
  %th.label
    %label{:for=>"page_#{meta_row[:field]}"}= t(meta_row[:field])
  %td.field= f.send(meta_row[:type], meta_row[:field], *meta_row[:args])
  %td.actions
    - if meta_row_counter+1 == @meta.size
      = link_to '#add_field_popup', :class=>'popup' do
        = image 'plus_grey', :alt => t('add_field')

app/views/admin/pages/_node.html.haml
%tr.page{:class =>'branch', :data => { :tt_branch => branch.to_s,  :tt_id => page.id, :tt_parent_id => parent_index, :tt_page_id => page.id}, :id => "page_#{page.id}"}
  - render_region :node, :locals => {:page => page, :level => level, :simple => simple} do |node|
    - node.title_column do
      %td.name
        %span.w1
          - if simple
            = node_title
          - else
            %i.far.fa-file
            = (link_to("#{node_title}".html_safe, edit_admin_page_path(page), :title => page.path)).html_safe
            = page_type
            = spinner
    - node.status_column do
      - unless simple
        %td.status
          %span.status{:class => "#{page.status.name.downcase}_status", :title => "#{timestamp(page.published_at) if page.published_at}"}= t(page.status.name.downcase)
    - node.actions_column do
      - unless simple
        %td.actions
          = page.add_child_option
          - if current_user.admin?
            = page.remove_option

app/views/admin/pages/_popups.html.haml
- content_for :popups do
  #popup_window
    .outer
      .content

  #add_part_popup.popup{:style => 'display: none'}
    #add_part_busy.busy{:style => 'display: none'}= image('spinner.gif', :alt => '')
    .popup_title= t('add_part')
    = form_for [:admin, PagePart.new] do |f|
      %p
        %label{:for => 'part_name_field'}= t('name')
        = f.text_field :name, :id => 'part_name_field', :maxlength => 100, :style => 'width: 15em', :class => 'textbox big'
        = hidden_field_tag 'index', 0, :id => 'page_part_index_field'
      .buttons
        = submit_tag t('add_part'), :id => 'add_part_button', :class => 'button'
        = t('or')
        = link_to 'Cancel', '#', onclick: 'Popup.close(); return false', class: 'cancel'
  #add_field_popup.popup{:style=>'display: none'}
    #add_field_busy.busy{:style=>'display: none'}= image('spinner.gif', :alt => '')
    .popup_title= t('add_field')
    = form_for [:admin, PageField.new], :html => { :onsubmit => 'event.stop(); addField(this)' } do |f|
      %p
        %label{:for=>'page_field_name'}= t('name')
        = f.text_field :name, :maxlength=>100, :class=>'textbox big', :style=>'width: 15em'
        = hidden_field_tag 'index', 2, :id=>'page_field_index_field'
        = hidden_field_tag 'page_field_counter', @page.fields.size
        = f.hidden_field :page_id, value: @page.id
      .buttons
        = submit_tag t('add_field'), :class=>'button', :id=>'add_page_field_button'
        = t('or')
        = link_to 'Cancel', '#', onclick: 'Popup.close(); return false', class: 'cancel'
  = render_region :popups

app/views/admin/pages/children.html.haml
- current_index = @index + 1
- parent_index = @index
- models.each do |child|
  - current_index = render_node child, current_index, parent_index
  - current_index += 1
= @rendered_html.html_safe

app/views/admin/pages/edit.html.haml
- @page_title = @page.title + ' - ' + default_page_title

- render_region :main do |main|
  - main.edit_header do
    %h1= ''
  - main.edit_form do
    = form_for @page, :as => :page, :url => admin_page_path(@page), :html => {:method => :put, :multipart => true, :id => 'edit_page', 'data-onsubmit_status'=>t('saving_changes')} do |fields|
      = render :partial => 'fields', :object => fields
  - main.edit_popups do
    = render :partial => 'popups'

app/views/admin/pages/index.html.haml
- @page_title = t('pages') + ' - ' + default_page_title

.outset
  = render_region :top
  %table.index.tablesaw#pages{:summary=>t('page_hierarchy')}
    %thead
      %tr
        - render_region :sitemap_head do |sitemap_head|
          - sitemap_head.title_column_header do
            %th.name= t('page')
          - sitemap_head.status_column_header do
            %th.status= t('status')
          - sitemap_head.actions_column_header do
            %th.actions= t('modify')
    %tbody
      - if @homepage
        = render_nodes(@homepage, 0).html_safe
      - else
        %tr.sortable
          %td.empty{:colspan => admin.page.index.node.length}= t('no_pages')
  = render_region :bottom

- unless @homepage
  #actions
    %ul
      %li
        = link_to new_admin_page_path, :class => 'action_button' do
          %i.fas.fa-plus-circle
          = t("new_homepage")

app/views/admin/pages/new.html.haml
- render_region :main do |main|
  - main.edit_header do
    %h1= t('new_page')
  - main.edit_form do
    = form_for @page, :as => :page, :url => admin_pages_path, :html => {:id => 'new_page', :multipart => true, 'data-onsubmit_status'=>'Creating page&#8230;'} do |f|
      = render :partial => 'fields', :object => f
  - main.edit_popups do
    = render :partial => 'popups'

app/views/admin/pages/remove.html.haml
- pages = @page.children.count > 1 ? t('pages') : t('page')
- body_classes << 'reversed'

%h1
  = t('remove_pages', :pages => pages)

%h4
  = t('text.pages.remove_warning', :pages => pages).html_safe

.inset
  %table.index#site_map
    %tbody
      - render_nodes @page, @page.id, nil, true
      = @rendered_html.html_safe

= form_for [:admin, @page.becomes(Page)], :html => {:method => :delete, 'data-onsubmit_status'=>'Removing pages&#8230;'} do
  .buttons
    %input.button{:type=>'submit', :value => t('delete_pages', :pages => pages) }/
    = t('or')
    = link_to t('cancel'), admin_pages_path, class: 'alt'