config/routes.rb
TrustyCms::Application.routes.draw do
  root to: 'site#show_page'
  devise_for :users, module: :devise, skip: :registration
  as :user do
    post 'authenticate', to: 'devise/sessions#create', as: :authenticate
  end
  get '/rad_social/mail' => 'social_mailer#social_mail_form', as: :rad_social_mail_form
  post '/rad_social/mail' => 'social_mailer#create_social_mail', as: :rad_create_social_mail
  TrustyCms::Application.config.enabled_extensions.each do |ext|
  end
  namespace :admin do
    resources :pages do
      resources :children, controller: 'pages'
      get 'remove', on: :member
    end
    resources :layouts do
      get 'remove', on: :member
    end
    resources :users do
      get 'remove', on: :member
    end
    resources :snippets do
      get :remove, on: :member
    end
    post 'save-table-position' => 'pages#save_table_position', as: 'save_tables_position'

    resources :assets do
      get :remove, on: :member
      get :refresh, on: :collection
      put :refresh, on: :member
    end
    resources :page_attachments, only: [:new] do
      get :remove, on: :member
    end
    resources :pages do
      get :remove, on: :member
      resources :page_attachments
    end
  end

  match 'admin/preview' => 'admin/pages#preview', :as => :preview, :via => %i[post put]
  get 'admin' => 'admin/pages#index'

  namespace :admin do
    resource :preferences
    resource :configuration, controller: 'configuration'
    resources :extensions, only: :index
    resources :page_parts
    resources :page_fields
    match '/reference/:type(.:format)' => 'references#show', :as => :reference, :via => :get

    resources :sites do
      get :remove, on: :member
      post :move_higher, on: :member
      post :move_lower, on: :member
      put :move_to_top, on: :member
      put :move_to_bottom, on: :member
    end
  end

  get 'error/404' => 'site#not_found', :as => :not_found
  get 'error/500' => 'site#error', :as => :error
  get '*url' => 'site#show_page'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pages, foreign_key: :created_by_id
  self.table_name = 'admins'

  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  alias_attribute :created_by_id, :id

  attr_accessor :skip_password_validation

  validate :password_complexity

  # Default Order
  default_scope { order('last_name') }

  # Associations
  belongs_to :created_by, class_name: 'User'
  belongs_to :updated_by, class_name: 'User'

  def role?(role)
    case role
    when :admin
      admin?
    when :designer
      designer?
    when :content_editor
      content_editor?
    else
      false
    end
  end

  def admin?
    admin
  end

  def designer?
    designer
  end

  def content_editor?
    content_editor
  end

  def locale
    'en'
  end

  def name
    "#{first_name} #{last_name}"
  end

  def password_required?
    return false if skip_password_validation

    super
  end

  def password_complexity
    return false if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,70}$/

    errors.add :password, 'Complexity requirement not met. Length should be 12 characters and include: 1 uppercase, 1 lowercase, 1 digit and 1 special character.'
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ResourceController
  paginate_models
  only_allow_access_to :index, :show, :new, :create, :edit, :update, :remove, :destroy,
                       when: :admin,
                       denied_url: { controller: 'pages', action: 'index' },
                       denied_message: 'You must have administrative privileges to perform this action.'

  before_action :ensure_deletable, only: %i[remove destroy]

  def show
    redirect_to edit_admin_user_path(params[:id])
  end

  def create
    user = User.new(user_params)
    if user.save
      flash[:notice] = 'User was created.'
      redirect_to admin_users_path
    else
      flash[:error] = 'There was an error saving the user. Please try again.'
      render :new
    end
  end

  def update
    user_params = params[model_symbol].permit!
    if user_params && user_params['admin'] == false && model == current_user
      user_params.delete('admin')
      announce_cannot_remove_self_from_admin_role
    end
    model.skip_password_validation = true unless user_params[:password_confirmation].present?
    if model.update(user_params)
      response_for :update
    else
      flash[:error] = 'There was an error saving the user. Please try again.'
      render :edit
    end
  end

  def ensure_deletable
    if current_user.id.to_s == params[:id].to_s
      announce_cannot_delete_self
      redirect_to admin_users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :admin, :designer,
                                 :password, :password_confirmation, :email, :site_id, :notes)
  end

  def announce_cannot_delete_self
    flash[:error] = t('users_controller.cannot_delete_self')
  end

  def announce_cannot_remove_self_from_admin_role
    flash[:error] = 'You cannot remove yourself from the admin role.'
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def roles(user)
    roles = []
    roles << I18n.t('admin') if user.admin?
    roles << I18n.t('designer') if user.designer?
    roles.join(', ')
  end
end

app/views/admin/users/_avatar.html.haml
#avatar
  = image_tag(gravatar_url(@user.email, :size=>'96px'), :class=>'avatar', :width=>96, :height=>96, :alt=>'')
  %p.caption
    Avatar provided by
    = link_to 'gravatar.com', 'http://gravatar.com/site/signup/'

app/views/admin/users/_choose_site.html.haml
- if current_user.admin?
  %label{:for=>'user_admin'} Can edit site
  = select :user, :site_id, [['<any>', '']] + Site.all.map { |s| [s.name, s.id] }
  .caption A user with no site is able to act (to whatever extent their status allows) on any site.

app/views/admin/users/_form.html.haml
= form_for [:admin, @user], :html => {class: 'user_form'} do |f|
  = render :partial => 'avatar' unless @user.new_record?

  = render_region :form_top, :locals => {:f => f}

  - render_region :form, :locals => {:f => f} do |form|
    - form.edit_first_name do
      = f.label :name, t('first_name')
      = f.text_field :first_name, :class => 'textbox', :maxlength => 100

    - form.edit_last_name do
      = f.label :name, t('last_name')
      = f.text_field :last_name, :class => 'textbox', :maxlength => 100

    - form.edit_email do
      = f.label :email, t('email_address') , :class => 'optional'
      = f.text_field 'email', :class => 'textbox', :maxlength => 255

    - form.edit_password do
      = render 'password_fields', :f => f

    - form.edit_roles do
      - if current_user.admin?
        %fieldset.multi_option
          %label= t('roles')
          = f.check_box 'admin', :class => 'checkbox'
          = f.label :admin, t('admin'), :class => 'checkbox'
          = f.check_box 'designer', :class => 'checkbox'
          = f.label :designer, t('designer'), :class => 'checkbox'

    - form.edit_notes do
      %fieldset
        = f.label :notes, t('notes'), :class => 'optional'
        ~ f.text_area 'notes', :size => '53x4', :class => 'textarea'

  - render_region :form_bottom, :locals => {:f => f} do |form_bottom|
    - form_bottom.edit_buttons do
      .page-actions
        = save_model_button(@user)
        = save_model_and_continue_editing_button(@user)
        = t('or')
        = link_to t('cancel'), admin_users_path, class: 'alt'
    - form_bottom.edit_timestamp do
      = updated_stamp @user

app/views/admin/users/_password_fields.html.haml
%fieldset#display_password{:style=> (@user.new_record? or !@user.valid?) ? 'display: none' : nil}
  %label= t('password')
  %span.value
    &bull;&bull;&bull;&bull;&bull;
  %a.button{:href=>'#', :onclick=>"$('#display_password').hide(); $('#change_password').show()"}= t('change')
%fieldset#change_password{:style=> (!@user.new_record? && @user.valid?) ? 'display: none' : nil}
  %p
    = f.label :password, t('new_password')
    = f.password_field 'password', :value => '', :maxlength => 40, :autocomplete => 'new-password'
  %p
    = f.label :password_confirmation, t('password_confirmation')
    = f.password_field 'password_confirmation', :value => '', :maxlength => 40, :autocomplete => 'new-password'
    - unless @user.new_record?
      %span
        = t('or')
        %a{:href=>'#', :class=>'cancel-button', :onclick=>" $('#display_password').show(); $('#change_password').hide()"}= t('cancel', class: 'alt')

app/views/admin/users/edit.html.haml
- @page_title = @user.name + ' ' + t('account') + ' - ' + default_page_title
- body_classes << 'edit_user'

- render_region :main do |main|
  - main.edit_header do
    %h1
      = t('edit_user')
  - main.edit_form do
    = render :partial => 'form'

app/views/admin/users/index.html.haml
- @page_title = t('users') + ' - ' + default_page_title

= render_region :top

.outset
  %table.index.tablesaw#users
    %thead
      %tr
        - render_region :thead do |thead|
          - thead.title_header do
            %th.user== #{t('name')} / #{t('username')}
          - thead.roles_header do
            %th.roles= t('roles')
          - thead.actions_header do
            %th.actions{:style=>'width:9em'}= t('modify')
    %tbody
      - @users.each do |user|
        %tr[user]
          - render_region :tbody, :locals => {:user => user} do |tbody|
            - tbody.title_cell do
              %td.name
                = link_to user.name, edit_admin_user_url(user)
            - tbody.roles_cell do
              %td.roles= roles(user)
            - tbody.actions_cell do
              %td.actions
                - if !current_user.admin?
                  %span.action.disabled
                    %i.fas.fa-minus-circle
                    = t('remove')
                - else
                  = link_to remove_admin_user_url(user), :class => 'action' do
                    %i.fas.fa-minus-circle
                    = t('remove')

- render_region :bottom do |bottom|
  - bottom.new_button do
    - if current_user.admin?
      #actions
        = pagination_for(@users)
        %ul
          %li
            = link_to new_admin_user_url, :class => 'action_button' do
              %i.fas.fa-plus-circle
              = t('new_user')

app/views/admin/users/new.html.haml
- render_region :main do |main|
  - main.edit_header do
    %h1
      = t('new_user')
  - main.edit_form do
    = render :partial => 'form'

app/views/admin/users/remove.html.haml
%h1= t('remove_user')

%h4
  = t('text.users.remove_warning').html_safe

%table.index#users
  %tbody
    %tr.node.level_1
      %td.user
        %span.title= @user.name

= form_for [:admin, @user], :html => { :method => :delete, 'data-onsubmit_status'=>'Removing user&#8230;' } do
  .buttons
    %input.button{:type=>'submit', :value => t('delete_user')}/
    = t('or')
    = link_to t('cancel'), admin_users_path, class: 'alt'